apiVersion: v1
kind: Secret
metadata:
  name: mcp-postgres-secret
type: Opaque
data:
  database: {{ .Values.postgres.env.POSTGRES_DB | default "mcp-gateway" | b64enc }}
  username: {{ .Values.postgres.env.POSTGRES_USER | default "postgres" | b64enc }}
  password: {{ .Values.postgres.env.POSTGRES_PASSWORD | default (randAlphaNum 10) | b64enc }}