{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metamcp.postgresFullname" . }}
  labels:
    {{- include "metamcp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "metamcp.postgresFullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "metamcp.postgresFullname" . }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "metamcp.postgresFullname" . }}-secret
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: data
          {{- if .Values.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "metamcp.postgresFullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metamcp.postgresFullname" . }}
  labels:
    {{- include "metamcp.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "metamcp.postgresFullname" . }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
# Convenience alias: some images default to connecting to host "postgres"
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "metamcp.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "metamcp.postgresFullname" . }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metamcp.postgresFullname" . }}-secret
  labels:
    {{- include "metamcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.auth.password | quote }}
{{- if and .Values.postgres.persistence.enabled (not .Values.postgres.persistence.storageClassName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metamcp.postgresFullname" . }}
  labels:
    {{- include "metamcp.labels" . | nindent 4 }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | default "1Gi" }}
{{- with .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
