{{- if .Values.auth.betterAuthSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metamcp.fullname" . }}-auth
  labels:
    {{- include "metamcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  BETTER_AUTH_SECRET: {{ .Values.auth.betterAuthSecret | quote }}
{{- end }}
