apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.web-env.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ (include "app.database.url" .) | b64enc | quote }}
  DIRECT_URL: {{ (include "app.database-migrations.url" .) | b64enc | quote }}
  {{- if .Values.web.extraEnvs }}
  {{- range $index, $map := .Values.web.extraEnvs }}
  {{ $map.name | upper | replace "-" "_" }}: {{ $map.value | toString | b64enc | quote }}
  {{- end }}
  {{- end }}
