apiVersion: v1
kind: Service
metadata:
  name: {{ include "codex-lb.fullname" . }}
  labels:
    {{- include "codex-lb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion }}
      appProtocol: http
      {{- end }}
  selector:
    {{- include "codex-lb.selectorLabels" . | nindent 4 }}
---
{{- if eq .Values.topology.mode "replicated" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codex-lb.handoffServiceName" . }}
  labels:
    {{- include "codex-lb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: {{ .Values.service.targetPort }}
      targetPort: http
      protocol: TCP
      {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion }}
      appProtocol: http
      {{- end }}
  selector:
    {{- include "codex-lb.selectorLabels" . | nindent 4 }}
---
{{- end }}
{{- if .Values.service.oauth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codex-lb.fullname" . }}-oauth
  labels:
    {{- include "codex-lb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.oauth.type }}
  ports:
    - name: oauth
      port: {{ .Values.service.oauth.port }}
      targetPort: oauth
      protocol: TCP
      {{- if and (or (eq .Values.service.oauth.type "NodePort") (eq .Values.service.oauth.type "LoadBalancer")) .Values.service.oauth.nodePort }}
      nodePort: {{ .Values.service.oauth.nodePort }}
      {{- end }}
  selector:
    {{- include "codex-lb.selectorLabels" . | nindent 4 }}
{{- end }}
