{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tolgee.fullname" . }}
  {{- with .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ . | quote }}
  {{- end }}
  labels:
    {{- include "tolgee.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "tolgee.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - path: {{ .Values.metrics.path | quote }}
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . | quote }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . | quote }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scheme }}
      scheme: {{ . | quote }}
      {{- end }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
      {{- if and (kindIs "string" .Values.metrics.port) (not (regexMatch "^[0-9]+$" .Values.metrics.port)) }}
      port: {{ .Values.metrics.port | quote }}
      {{- else }}
      targetPort: {{ printf "%v" .Values.metrics.port | int }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ . | quote }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
