{{- /*
Validation: if metamcp.enabled=false, no server may have register.enabled=true (default true).
This prevents silently skipping registration while the user expects it.
*/ -}}
{{- $mm := .Values.metamcp -}}
{{- $mmDisabled := false -}}
{{- if kindIs "map" $mm -}}
  {{- if kindIs "bool" $mm.enabled -}}
    {{- $mmDisabled = (not $mm.enabled) -}}
  {{- end -}}
{{- end -}}
{{- if $mmDisabled -}}
  {{- $bad := list -}}
  {{- range $i, $s := (default (list) .Values.servers) -}}
    {{- $reg := (get $s "register") -}}
    {{- $regMap := ternary $reg (dict) (kindIs "map" $reg) -}}
    {{- /* default register.enabled=true when omitted */ -}}
    {{- $regEnabled := (default true ($regMap.enabled)) -}}
    {{- if $regEnabled -}}
      {{- $name := ($s.name | default (printf "srv-%d" $i)) -}}
      {{- $bad = append $bad $name -}}
    {{- end -}}
  {{- end -}}
  {{- if gt (len $bad) 0 -}}
    {{- fail (printf "metamcp.enabled=false but these servers have register.enabled=true: %s. Either set metamcp.enabled=true or set register.enabled=false for these servers." (join ", " $bad)) -}}
  {{- end -}}
{{- end -}}
