{{- range $i, $srv := .Values.servers }}
{{- if and (hasKey $srv "cache") ($srv.cache.enabled | default false) (eq (default "" $srv.cache.pvc.existingClaim) "") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-cache-%s" (include "mcp-server.fullname" $) (($srv.name | default (printf "%d" $i)) | trunc 40 | trimSuffix "-") }}
  labels:
    {{- include "mcp-server.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- toYaml ($srv.cache.pvc.accessModes | default (list "ReadWriteOnce")) | nindent 4 }}
  {{- with $srv.cache.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ $srv.cache.pvc.size | default "1Gi" }}
{{- end }}
{{- end }}

