{{- $gw := .Values.transport.stdioGateway -}}
{{- $hasServers := gt (len $gw.servers) 0 -}}
{{- $hasRaw := and $gw.namedServersJson (ne $gw.namedServersJson "") -}}
{{- if and (eq .Values.transport.type "stdio") $gw.enabled (or $hasServers $hasRaw) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-server.fullname" . }}-gateway
  labels:
    {{- include "mcp-server.labels" . | nindent 4 }}
data:
  servers.json: |
    {{- if $hasRaw }}
    {{ $gw.namedServersJson | nindent 4 }}
    {{- else }}
    {{- /* Build JSON from values.servers map */ -}}
    {{- $servers := dict -}}
    {{- range $name, $srv := $gw.servers }}
      {{- $envmap := dict -}}
      {{- range $e := ($srv.env | default (list)) }}
        {{- $_ := set $envmap $e.name $e.value -}}
      {{- end }}
      {{- $obj := dict "command" $srv.command "args" ($srv.args | default (list)) -}}
      {{- if $srv.env }}{{- $_ := set $obj "env" $envmap -}}{{- end }}
      {{- if hasKey $srv "disabled" }}{{- $_ := set $obj "disabled" $srv.disabled -}}{{- end }}
      {{- $_ := set $servers $name $obj -}}
    {{- end }}
    {{- (dict "mcpServers" $servers) | toJson | nindent 4 }}
    {{- end }}
{{- end }}

