{{- if .Values.oban.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codex-pooler.fullname" . }}-oban-scheduler
  labels:
    {{- include "codex-pooler.labels" . | nindent 4 }}
    app.kubernetes.io/component: oban-scheduler
spec:
  replicas: {{ .Values.oban.scheduler.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.oban.scheduler.strategy.maxUnavailable }}
      maxSurge: {{ .Values.oban.scheduler.strategy.maxSurge }}
  selector:
    matchLabels:
      {{- include "codex-pooler.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: oban-scheduler
  template:
    metadata:
      labels:
        {{- include "codex-pooler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: oban-scheduler
        {{- if and .Values.clustering.enabled .Values.clustering.participants.scheduler }}
        {{- include "codex-pooler.clusteringMemberLabel" . | nindent 8 }}
        {{- end }}
    spec:
      {{- if and .Values.clustering.enabled .Values.clustering.participants.scheduler }}
      subdomain: {{ include "codex-pooler.clusteringHeadlessServiceName" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.oban.scheduler.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "codex-pooler.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: oban-scheduler
          image: {{ include "codex-pooler.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if and .Values.clustering.enabled .Values.clustering.participants.scheduler }}
          ports:
            - name: epmd
              containerPort: {{ .Values.clustering.epmdPort }}
            - name: distribution
              containerPort: {{ .Values.clustering.distributionPort }}
          {{- end }}
          env:
            - name: OBAN_MODE
              value: scheduler
            {{- include "codex-pooler.clusteringEnv" (dict "root" . "role" "scheduler") | nindent 12 }}
            {{- include "codex-pooler.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.oban.scheduler.resources | nindent 12 }}
      {{- with .Values.oban.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oban.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oban.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
