{{- if .Values.oban.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codex-pooler.fullname" . }}-oban-worker
  labels:
    {{- include "codex-pooler.labels" . | nindent 4 }}
    app.kubernetes.io/component: oban-worker
spec:
  replicas: {{ .Values.oban.worker.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.oban.worker.strategy.maxUnavailable }}
      maxSurge: {{ .Values.oban.worker.strategy.maxSurge }}
  selector:
    matchLabels:
      {{- include "codex-pooler.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: oban-worker
  template:
    metadata:
      labels:
        {{- include "codex-pooler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: oban-worker
        {{- if and .Values.clustering.enabled .Values.clustering.participants.worker }}
        {{- include "codex-pooler.clusteringMemberLabel" . | nindent 8 }}
        {{- end }}
    spec:
      {{- if and .Values.clustering.enabled .Values.clustering.participants.worker }}
      subdomain: {{ include "codex-pooler.clusteringHeadlessServiceName" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.oban.worker.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "codex-pooler.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: oban-worker
          image: {{ include "codex-pooler.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if and .Values.clustering.enabled .Values.clustering.participants.worker }}
          ports:
            - name: epmd
              containerPort: {{ .Values.clustering.epmdPort }}
            - name: distribution
              containerPort: {{ .Values.clustering.distributionPort }}
          {{- end }}
          env:
            - name: OBAN_MODE
              value: worker
            {{- include "codex-pooler.clusteringEnv" (dict "root" . "role" "worker") | nindent 12 }}
            {{- include "codex-pooler.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.oban.worker.resources | nindent 12 }}
      {{- with .Values.oban.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oban.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oban.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
