apiVersion: v1
kind: Service
metadata:
  name: {{ include "multica.frontendServiceName" . }}
  labels:
    {{- include "multica.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  {{- with .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.frontend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.frontend.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.frontend.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "multica.componentSelectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
