{{- include "multica.validate" . -}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "multica.fullname" . }}
  labels:
    {{- include "multica.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $.Values.ingress.backendPaths.enabled }}
          {{- range $.Values.ingress.backendPaths.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "multica.backendServiceName" $ }}
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
          {{- end }}
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "multica.frontendServiceName" $ }}
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
