# Minimal MetaMCP values for e2e (provision)
auth:
  betterAuthSecret: dev-secret
env:
  APP_URL: http://localhost:12008
users:
  - email: admin@example.com
    password: change-me
    name: Admin
disablePublicSignup: true

provision:
  enabled: true
  servers:
    - name: stdio-everything
      type: STDIO
      command: ["npx","-y","@modelcontextprotocol/server-everything","stdio"]
    - name: http-everything
      type: STREAMABLE_HTTP
      url: http://ext-http.{{ .Release.Namespace }}.svc.cluster.local:3001/mcp
    - name: sse-everything
      type: SSE
      url: http://ext-sse.{{ .Release.Namespace }}.svc.cluster.local:3002/sse
  namespaces:
    - name: lab
      servers: ["stdio-everything","http-everything","sse-everything"]
  endpoints:
    - name: lab
      namespace: lab
      transport: SSE
