# Advanced server provisioning exercising most per-server options.
# Note: Secrets/ConfigMaps referenced here should be created separately.

auth:
  betterAuthSecret: dev-secret

users:
  - email: admin@example.com
    password: change-me
    name: Admin

provision:
  enabled: true
  servers:
    - name: http-everything
      type: STREAMABLE_HTTP
      port: 3001
      node:
        image: node
        tag: 24-alpine
        package: "@modelcontextprotocol/server-everything"
        version: "latest"
        args: ["streamableHttp"]
      resources:
        requests: { cpu: "100m", memory: "128Mi" }
        limits:   { cpu: "500m", memory: "512Mi" }
      readinessProbe:
        httpGet: { path: "/mcp", port: "http" }
        initialDelaySeconds: 2
        periodSeconds: 5
      livenessProbe:
        tcpSocket: { port: "http" }
        initialDelaySeconds: 10
        periodSeconds: 10
      envFrom:
        - secretRef: { name: http-everything-env }  # optional
      podLabels:
        app.kubernetes.io/part-of: metamcp
      podAnnotations:
        example/icore: "true"
      imagePullSecrets:
        - name: regcred
      serviceAccountName: ""
      podSecurityContext: {}
      securityContext: {}
      nodeSelector:
        kubernetes.io/os: linux
      tolerations: []
      affinity: {}
      extraVolumes:
        - name: cfg
          configMap: { name: http-everything-config }
      extraVolumeMounts:
        - name: cfg
          mountPath: /app/config
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 70

    - name: sse-everything
      type: SSE
      port: 3001
      node:
        package: "@modelcontextprotocol/server-everything"
        version: "latest"
        args: ["sse"]
      initContainers:
        - name: wait-a-bit
          image: busybox:1.36
          command: ["/bin/sh","-lc","echo init && sleep 1"]
      cache:
        enabled: true
        mountPath: /cache
        pvc:
          existingClaim: sse-everything-cache  # or provide size to let the chart create one
      readinessProbe:
        tcpSocket: { port: "http" }
        initialDelaySeconds: 2
        periodSeconds: 5
      livenessProbe:
        httpGet: { path: "/sse", port: "http" }
        initialDelaySeconds: 10
        periodSeconds: 10

  namespaces:
    - name: lab
      servers: ["http-everything","sse-everything"]

  endpoints:
    - name: lab
      namespace: lab
      transport: SSE

