{{- if .Values.pgbouncerExporter.podMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.selectorLabels" . | nindent 8 }}
spec:
  selector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 8 }}
  podMetricsEndpoints:
    - port: exporter
{{- end }}
