{{- if not .Values.config.existingAdminSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-secret
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  adminUser: {{ required "A valid .Values.config.adminUser entry required!" .Values.config.adminUser | b64enc | quote }}
  adminPassword: {{ required "A valid .Values.config.adminPassword entry required!" .Values.config.adminPassword | b64enc | quote }}
{{- end }}
