{{- if not .Values.config.existingUserlistSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-userlist-secret
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  userlist.txt: {{ include "pgbouncer.secret.userlist" . | trim | b64enc }}
{{- end -}}
