{{- if .Values.web.ingress.enabled -}}
{{- $fullName := include "app.web.name" . -}}
{{- $fullTLSName := include "app.web-tls.name" . -}}
{{- $svcPort := .Values.web.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.web.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.web.ingress.ingressClassName }}
{{- if .Values.web.ingress.tls }}
  tls:
  {{- range .Values.web.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ $fullTLSName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.web.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
