{{- if .Values.web.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.web.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.web.service.type "NodePort") (not (empty .Values.web.service.nodePort))) }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
  selector:
    {{- include "app.web.selectorLabels" . | nindent 4 }}
{{- end }}
