# Example: Gateway API HTTPRoute for WebSocket
# Requires a Gateway named "gateway" with an HTTP listener named "http" in your cluster.

service:
  port: 3000

container:
  port: 3000

transport:
  type: websocket
  http:
    wsPath: /ws

httpRoute:
  enabled: true
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - mcp.example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: 3600s
        backendRequest: 3600s

