# Example: Chrome DevTools MCP server using stdio bridge
# Purpose: Shows how to run stdio-only Node.js MCP servers in Kubernetes
# using the built-in stdioBridge feature with mcp-proxy

servers:
  - name: chrome-devtools-stdio
    port: 3000
    stdioBridge:
      enabled: true
      image: ghcr.io/icoretech/mcp-stdio-bridge
      tag: 0.2.1
      port: 3000
      passEnvironment: true
      serverCommand: ["npx", "chrome-devtools-mcp"]
      serverArgs: []  # No additional args needed
    register:
      enabled: false

# The mcp-proxy bridge keeps the stdio server alive and converts to HTTP transport
# Gateway is managed by the Unla subchart (Service: <release-name>, port 5235)
