# Example: stdio gateway exposing two named servers under /servers/{name}/sse
mode: python
python:
  image: ghcr.io/astral-sh/uv:latest
  package: awslabs.aws-documentation-mcp-server@latest
  args: ["--port","3000"]

service:
  port: 3000

transport:
  type: stdio
  stdioGateway:
    enabled: true
    image: ghcr.io/sparfenyuk/mcp-proxy:latest
    passEnvironment: true
    allowOrigins: ["*"]
    # Install servers at startup (inside the gateway container)
    preStart:
      - pip install --no-cache-dir awslabs.aws-documentation-mcp-server awslabs.aws-pricing-mcp-server
    # Expose multiple stdio servers by name
    servers:
      docs:
        command: awslabs.aws-documentation-mcp-server
        args: []
      pricing:
        command: awslabs.aws-pricing-mcp-server
        args: []

ingress:
  enabled: false
