{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inngest.fullname" . }}-pvc
  labels:
    {{- include "inngest.labels" . | nindent 4 }}
  {{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}

spec:
  accessModes:
{{ toYaml .Values.persistence.accessModes | indent 4 }}

  {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}
  {{- end }}

  {{- if .Values.persistence.volumeMode }}
  volumeMode: "{{ .Values.persistence.volumeMode }}"
  {{- end }}

  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
