apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inngest.fullname" . }}-secret
  labels:
    {{- include "inngest.labels" . | nindent 4 }}
type: Opaque
stringData:
  eventKey: {{ .Values.config.eventKey | quote }}
  signingKey: {{ .Values.config.signingKey | quote }}
