name: mcp-server e2e

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: latest
      - name: Setup kind
        uses: helm/kind-action@v1
        with:
          version: v0.24.0
          kubectl_version: v1.30.0
      - name: Run e2e
        run: |
          chmod +x hack/e2e/e2e.sh
          ./hack/e2e/e2e.sh
